import Head from 'next/head'
import Image from 'next/image'
import React, { useState } from 'react';
import { Inter } from 'next/font/google'
import Navbar from '@/componets/Navbar/Navbar'
import About from '@/componets/About/About'
import Services from './../componets/Services/Services';
import Clients from '@/componets/Clients/Clients'
import Filter from '@/componets/Filter/Filter'
import Schedule from '@/componets/Schedule/Schedule'
import Reviews from '@/componets/Reviews/Reviews'
import Questions from '@/componets/Questions/Questions'
import Contacts from '@/componets/Contacts/Contacts'
import ModalMain from '@/componets/Modal/ModalMain';


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [openValue, setOpenValue] = useState<boolean>(false);
  const [contentNum, setContentNum] = useState<number>(0);
  const OpenModal = () => {
    setOpenValue(true)
    setContentNum(0)
  }
  const ShowModal = (val: number) => {
    setOpenValue(true)
    setContentNum(val)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar ShowModal={ShowModal} />
      <div className="back">
        <About />
        <Services />
        <Clients />
        <Filter />
        <Schedule OpenModal={OpenModal} />
        <Reviews />
        <Questions />
        <Contacts />
      </div>
      {
        openValue && <ModalMain
          openValue={openValue}
          contentNum={contentNum}
          ChangeOpen={(val: boolean) => setOpenValue(val)} />
      }

    </>
  )
}
