export enum NavLinkText {
  SignUp = 'Sign up',
  SignIn = 'Sign in',
  Logout = 'Logout',
  Orders = 'Orders',
  Blacklist = 'Blacklist',
  Security = 'Security',
  Reviews = 'Reviews',
  Payment = 'Payment',
  Offer = 'Offer',
  Users = 'Users',
  MultipleOrders = 'Multiple Orders',
  AddWorker = 'Add Worker',
  InactiveUsers = 'Inactive users',
  NotVerified = 'Not verified',
  Reservation = 'Reservation',
  PaymentStatus = 'Payment status',
  Holidays = 'Holidays',
  Rats = 'Rats',
  MapView = 'MapView',
  Calendar = 'Calendar',
  Rights = '© Anna, 2021. All rights reserved',
  AboutUs = 'About Us',
  WhatsApp = 'WhatsApp',
  Conditions = 'Conditions of use',
  Applications = 'Download our application:',
}
