import Head from "next/head";
import React, { useState } from "react";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar/Navbar";
import Main from "@/components/Main/Main";
import About from "@/components/About/About";
import Section from "@/components/Section/Section";
import Services from "@/components/Services/Services";
import Filter from "@/components/Filter/Filter";
import Schedule from "@/components/Schedule/Schedule";
import Reviews from "@/components/Reviews/Reviews";
import Footer from "@/components/Footer/Footer";
import ModalMain from "@/components/Modal/ModalMain";
const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const [openValue, setOpenValue] = useState<boolean>(false);
  const [contentNum, setContentNum] = useState<number>(0);
  const OpenModal = () => {
    setOpenValue(true);
    setContentNum(0);
  };
  const ShowModal = (val: number) => {
    setOpenValue(true);
    setContentNum(val);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar ShowModal={ShowModal} />
      <Main />
      <About />
      <Section />
      <Services />
      <Filter />
      <Schedule OpenModal={OpenModal} />
      <Reviews />
      <Footer />
      {openValue && (
        <ModalMain
          openValue={openValue}
          contentNum={contentNum}
          ChangeOpen={(val: boolean) => setOpenValue(val)}
        />
      )}
    </>
  );
}
